### PR TITLE
added keepalive socket option to all connections

### PR DESCRIPTION
**Pull request by xroot88**
JIRA:NCP-1839

(waffles) alexm@alexm-dev:~/aiclib$ nosetests tests.unit.test_core
.......
----------------------------------------------------------------------
Ran 7 tests in 0.008s

OK

### CODE REVIEW

**Comment by xroot88** [comment]
** DO NOT MERGE **

**Comment by andyhky** [comment]
Looks good to me, thanks for the quick fix.

**Comment by roaet** [comment]
Can this be merged?

**Comment by xroot88** [comment]
this can be merged

**Pull request merged**
